### ISSUE TITLE
Missing major scheme implementations 

### ISSUE THREAD

**Issue by spdegabrielle** [dundalek/awesome-lisp-languages#1]
Missing major scheme implementations; Bigloo, Chez, Chicken, Guile & Racket.

**Comment by dundalek** [comment]
Thanks for suggestions. I did not know about Bigloo, that is definitely a fit because it seems to run also on JVM and .NET. I need to figure out how to present it, whether to list it multiple times in each category or whether to create some additional category.

I was aware of the other ones and really like Racket for example. My initial focus was to collect non-traditional implementations.

But for completeness I guess I need to find a way to mention major traditional implementations but not to overshadow the experimental ones. Because one could say that all traditional implementations are hosted as well because they usually include C/C++ ffi :)
