### ISSUE TITLE
Add Type-C javascript targetting language Wisp

### ISSUE THREAD

**Issue by chr15m** [dundalek/awesome-lisp-languages#4]
https://github.com/Gozala/wisp

**Comment by chr15m** [comment]
BTW you might be able to mine this report for more Type-C entries:

https://github.com/chr15m/awesome-clojure-likes/blob/master/README.md

**Comment by dundalek** [comment]
Thanks for the suggestion. Wisp looks neat! I will add it so that ClojureScript does not feel so lonely by itself :)

You have also I cool report, I will definitely put in a link to it. If I have discovered it sooner I might have saved myself the effort and might not do mine :) Anyway it is great that so many cool projects exist and that people bring even more I did not hear about before into my attention.

**Comment by chr15m** [comment]
Agree! The more the merrier. :)
